## build_single_file.R -- assemble contract_year.R from the nine pipeline scripts.
##
## contract_year.R is a BUILD PRODUCT, not a second copy to maintain. Edit
## R/*.R, then run this from the repository root. Verification is separate:
## run both versions and diff the logs.

## Paths are relative to the repository root; run this from there.
SRC  <- "R"
DEST <- "contract_year.R"

parts <- c(
  "00_functions.R"          = "ESTIMATION ENGINE AND HELPERS",
  "01_build.R"              = "BUILD THE PANEL AND GATE THE DATA",
  "02_models.R"             = "ESTIMATES",
  "03_tables.R"             = "EXPORT TABLES 1-6, 8, A1 (machine-readable .tex/.csv)",
  "04_verify.R"             = "VERIFY EVERY ESTIMATE AGAINST THE CORRECTED SERIES",
  "05_table7.R"             = "TABLE 7, CAREER STAGE: LADDER, SATURATION, BOOTSTRAP",
  "06_manuscript.R"         = "REMAINING FIGURES QUOTED IN THE MANUSCRIPT",
  "07_manuscript_tables.R"  = "TABLES 1-8 IN THE MANUSCRIPT'S OWN LATEX STYLE",
  "08_endogeneity.R"        = "ENDOGENEITY OF CONTRACT YEAR TIMING (Section 6.7)")

## A guard is an `if (...) stop(...)` naming another script, plus the
## `.need <-` line feeding it. Safe to drop here: in one file the objects
## always exist by the time they are referenced.
##
## Extents come from R's parser, not from counting parentheses. A guard's
## condition closes its parens on its own line while the stop() call continues
## on the next, so a paren counter stops one line early and leaves a dangling
## `.need` reference that only surfaces at run time.
strip_guards <- function(path) {
  x  <- readLines(path, warn = FALSE, encoding = "UTF-8")
  ex <- parse(path, keep.source = TRUE)
  sr <- attr(ex, "srcref")
  drop <- logical(length(x))
  for (k in seq_along(ex)) {
    txt <- paste(as.character(sr[[k]]), collapse = " ")
    is_guard <-
      grepl('^\\s*\\.need\\s*<-', txt) ||
      (grepl('!exists\\("(PIPELINE_VERSION|M|d|LADDER|LEADLAG)"', txt) &&
       grepl('\\bstop\\(', txt))
    if (is_guard) drop[sr[[k]][1]:sr[[k]][3]] <- TRUE
  }
  x <- x[!drop]
  ## collapse the double blank line a removed guard leaves behind
  x[!(c(FALSE, head(x, -1) == "") & x == "")]
}

banner <- function(n, total, title) c(
  "",
  strrep("#", 78),
  sprintf("## PART %d OF %d  --  %s", n, total, title),
  strrep("#", 78),
  "")

## Header: everything run_all.R does before its first source() call.
header <- c(
'## The Contract Year Phenomenon Revisited -- Atkins & Dikgang',
'## Complete R replication, single file. Base R only, no packages.',
'##',
'##   Rscript contract_year.R',
'##',
'## NEEDS Clean_Data.csv beside this script or in ./data/. Two extracts',
'## circulate under that name, differing in one service time value (Cervelli',
'## 2018: 7.622093 vs 0.622093). Part 2 repairs the bad one, so either gives',
'## identical results, and the run reports which it found.',
'##',
'## WRITES to ./output/: the run log, the constructed panel, results_ledger.csv,',
'## manuscript_facts.csv, and the tables as .tex and .csv.',
'##',
'## Runtime is about a minute; the bootstrap in Part 6 accounts for most of it.',
'##',
'## GENERATED by build_single_file.R from R/. Edit those and rebuild rather',
'## than patching here, or the two versions drift.',
'',
'rm(list = ls())',
'set.seed(12345)',
'options(stringsAsFactors = FALSE, width = 100)',
'',
'## PART 0 -- configuration. Edit this block only.',
'',
'## Forward slashes only: "C:\\Users\\..." is read as escape sequences and fails.',
'## Falls back to CY_PROJ, then getwd().',
'PROJ <- "C:/Users/atkin/OneDrive/Desktop/Stata"',
'',
'## Career-stage cutoff in years of service. Five puts 524 of 528 free agency',
'## seasons on the veteran side; six puts 341.',
'VET_CUTOFF <- 5',
'',
'BOOT_B <- 2000L',
'',
'',
'if (!dir.exists(PROJ)) {',
'  alt  <- Sys.getenv("CY_PROJ")',
'  PROJ <- if (nzchar(alt) && dir.exists(alt)) alt else getwd()',
'}',
'PROJ <- normalizePath(PROJ, winslash = "/", mustWork = TRUE)',
'',
'## PrelimData*.csv is the older uncorrected extract: last resort, with a',
'## warning.',
'find_csv <- function(root) {',
'  dirs  <- c(root, file.path(root, "data"))',
'  dirs  <- dirs[dir.exists(dirs)]',
'  hit   <- file.path(dirs, "Clean_Data.csv")',
'  hit   <- hit[file.exists(hit)]',
'  if (length(hit)) return(list(path = hit[1], legacy = FALSE))',
'  glob <- unlist(lapply(dirs, function(p)',
'    list.files(p, "^Clean[_ ]?Data.*\\\\.csv$", full.names = TRUE, ignore.case = TRUE)))',
'  if (length(glob)) return(list(path = glob[1], legacy = FALSE))',
'  old <- unlist(lapply(dirs, function(p)',
'    list.files(p, "^PrelimData.*\\\\.csv$", full.names = TRUE)))',
'  if (length(old)) return(list(path = old[1], legacy = TRUE))',
'  list(path = NA_character_, legacy = FALSE)',
'}',
'.csv   <- find_csv(PROJ)',
'RAWCSV <- .csv$path',
'if (is.na(RAWCSV))',
'  stop("Clean_Data.csv not found. Searched:\\n  ", PROJ, "\\n  ",',
'       file.path(PROJ, "data"),',
'       "\\nPut the CSV in one of those, or set RAWCSV by hand after this block.")',
'if (isTRUE(.csv$legacy))',
'  warning("Found only PrelimData*.csv, the older UNCORRECTED extract. Its ",',
'          "Cervelli 2018 service time is wrong and the fingerprint gate in ",',
'          "Part 2 will fail. Use Clean_Data.csv.", call. = FALSE)',
'',
'OUTDIR <- file.path(PROJ, "output")',
'dir.create(OUTDIR, showWarnings = FALSE, recursive = TRUE)',
'if (file.access(OUTDIR, 2) != 0)',
'  stop("No write permission for ", OUTDIR,',
'       "\\nIf this is a synced OneDrive folder, pause syncing or choose another OUTDIR.")',
'',
'logfile <- file.path(OUTDIR, "contract_year_analysis.log")',
'con <- file(logfile, open = "wt", encoding = "UTF-8")',
'sink(con, split = TRUE)',
'',
'cat("THE CONTRACT YEAR PHENOMENON REVISITED IN THE STATCAST ERA\\n")',
'cat("Atkins & Dikgang | R replication, single file\\n")',
'cat("Run:  ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\\n")',
'cat("R:    ", R.version.string, "on", .Platform$OS.type, "\\n")',
'cat("Proj: ", PROJ, "\\n")',
'cat("Data: ", RAWCSV, "\\n")',
'cat("Out:  ", OUTDIR, "\\n")',
'cat("Cut:  ", VET_CUTOFF, "years of service;  bootstrap replicates:", BOOT_B, "\\n")')

footer <- c(
'',
strrep("#", 78),
'## DONE',
strrep("#", 78),
'',
'cat("\\n")',
'cat(strrep("=", 70), "\\n", sep = "")',
'cat("DONE ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\\n", sep = "")',
'cat(strrep("=", 70), "\\n", sep = "")',
'cat("  Log:    ", logfile, "\\n")',
'cat("  Panel:  ", file.path(OUTDIR, "contract_year_clean.csv"), "\\n")',
'cat("  Ledger: ", file.path(OUTDIR, "results_ledger.csv"), "\\n")',
'cat("  Facts:  ", file.path(OUTDIR, "manuscript_facts.csv"), "\\n")',
'cat("  Tables: ", file.path(OUTDIR, "table1 - table8, tableA1 (.tex/.csv)"), "\\n")',
'cat("          ", file.path(OUTDIR, "tables_manuscript.tex"), "\\n")',
'cat("\\n  Table 7 needs \\\\usepackage{booktabs} and\\n")',
'cat("  \\\\usepackage[flushleft]{threeparttable} in the manuscript preamble.\\n")',
'cat("  Tables 1-8 in tables_manuscript.tex need booktabs only.\\n")',
'',
'sink(); close(con)',
'cat("Complete. See", logfile, "\\n")')

## ---------------------------------------------------------------------------
out <- header
for (i in seq_along(parts)) {
  fn <- names(parts)[i]
  n0 <- length(readLines(file.path(SRC, fn), warn = FALSE))
  x  <- strip_guards(file.path(SRC, fn))
  out <- c(out, banner(i, length(parts), unname(parts[i])),
           sprintf("## Source: R/%s", fn), "", x)
  cat(sprintf("  %-24s %4d lines -> %4d\n", fn, n0, length(x)))
}
out <- c(out, footer)

## No non-ASCII: the file has to survive a Windows console in CP1252.
bad <- grep("[^\x01-\x7f]", out)
if (length(bad)) {
  cat("\n  NON-ASCII on lines:", paste(bad, collapse = ", "), "\n")
  print(out[bad])
  stop("Non-ASCII characters in the assembled file.")
}

writeLines(out, DEST, useBytes = TRUE)
cat(sprintf("\n  wrote %s  (%d lines)\n", DEST, length(out)))

## Parse check: catches a strip that removed one line too many.
invisible(parse(DEST))
cat("  parses cleanly.\n")
